### ISSUE TITLE
new messenger update makes messages unreadable

### ISSUE THREAD

**Issue by dragunonov** [Kasjonus/SidebarMessegerFix#7]
messages now appear as light grey text in plain white background and can only be read when highlighted. issue only affects messages sent to me, not messages i send to others. example pic attached
![Screenshot 2023-10-24 114949](https://github.com/Kasjonus/SidebarMessengerFix/assets/148856209/dd801564-4496-4ea2-bcaa-b4a74b07dec6)

**Comment by Kasjonus** [comment]
Currently I wait to approve update by Opera add-ons, but, if you want update now, you can download release 0.4.3 from github and add to browser by this tutorial https://github.com/Kasjonus/SidebarMessengerFix#use

**Comment by Kasjonus** [comment]
Today Opera approved my update, it's avaiable to download from Opera add-ons :)

[addons.opera.com/extensions/details/fix-for-sidebar-facebook-messsengertm/](https://addons.opera.com/extensions/details/fix-for-sidebar-facebook-messsengertm/)
